
# only build the deploy branch
branches:
  only:
    - deploy

# needs both a current nodejs (with ES6 support) and ruby >=2.2
language: node_js
node_js:
  - "7"

before_install:
  - rvm install 2.2
  - npm install
  - npm install -g gulp

install: gem install jekyll

script: gulp build 

deploy:
  provider: s3
  access_key_id:
    secure: "5w67IgUozudWwMM7eDuDR2icHGYR2sx1eWC14RI6da7Kuvx0b/Hp6KFBmGnoL+M9F+8W+RSGNI2tBKZQhH5roauPjTbsYIukhlzCegua+NLcZpOeb6zYKZNUP4h07qKTQamUBWjFH2g0dnRlzLsz5NPB3wq4bgFUM5kOBBKBRN3LrdIdr2n3AffJjI/CUNLz04Wgk97m3BiAZQToJ54WhK6nCEh56WfVO9eMrmheerhsWz2ereQk76e85t0Uupb5owtVtFLp5qH1N3m0/HFpskU9lNwwoG+zfPy1AcFqV+o4GqIwTmMSz8B5s40R0OwssGtqfL21CSXMxKlqcc6e889y1UQEiuyVZ4aiGF2FN2mdq4uVvbM2rA5+hE6qpbz7ul3jwfbUx1q6aKsWx7/rzO+ikEOAXj1l3jktvLoaX6LSPayCQ+eehHXwd5mvQCJ5EZGHpe4vcgnDOoTcUqc0lgt9fpB9jcW5QJJkDa2PJFzFdvC3FyXlfkyo156HOWUZHeoAnivfU3HgZBvExt2tCDrcXaZ0sF7Tuqh9NVI1AjKQBow1x4G5dCq5w02guMRnb7bZDOSPvmUsT8ZX9AiVJ36x0y8n/TSECeWZ3KxRlJCEpV7FBMy/spGRcmO9hJ85uKLk3JLc5A7nunjGb/Rqt+dcWcaDB8Zg1Vb7FF+urTI="
  secret_access_key:
    secure: "SmQfG6vbYFZeH30LFt+yCHEN44iJ8sNwo0Bm3FswQC9NFAAQFDXW+hA+JPf/9sqoTlonG71lGCTqgnAj348k94k9XVnymy2Wx9Mogt2UBkx8d1RWM559PyjjlHvtXSykku3daDuL/UbPR7lgu3SdqYLtOAd0w4HUHW9j8GeOY6nFHqtrmsqYMY2wztx4CzLmLqbMGZBKpgj7rsw+BPsAgeI34CTLXwmFg2WVS8Ii5uccPCm5j92nLJFniEEA4/2d2toKfk7JVyDi4YC240wSTG4OL4OFl9DMfPSO88gAZmjlbesM/qjx0H58JAq5kwas2VzGMc+1BW8qANvN98POhEudLjFx8i3KNnLBZe8G6tuwJV5aOYL+Gvu4rLNuDlig4zrdrDFHXg0gV8m7DwogB90vGIa1Qo1/nrGNKZw8geHEet33iDLQXlWAeZsie5AMHd29uURjRrZ7BAABtu5ACT8vYCUnNVl1+ZjyXTxXyiw3gxbH+GVlodGWYZXEoq83yx9kJ1Qm0hthbKpRwMtukYkkuum8XYZFi/0ixN7EfrM5iiGJqm1/dLGRMCd5Wx9M9+DAskkirqaAC7w0ub1yYNBki2hV+vm85unqsUUJApxH0DTOdmxfArtWJS/KJMqOfxqKtM3usnMRIETCf/rlxGUyTT7YaEIzFgB1BIIb5wA="
  bucket: "kowi.onehot.de"
  skip_cleanup: true
  region: eu-central-1
  local_dir: src
  on: 
    branch: deploy
    repo: mumogu/gulp-jekyll-boilerplate
#  acl: public_read

