version: 0.1

phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y ruby2.2
      - sudo gem2.2 install jekyll
  pre_build:
    commands:
      - npm install -g gulp
      - npm install
  build:
    commands:
      - gulp build
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - dist/