version: 0.1

phases:
  install:
    commands:
      - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
      - \curl -sSL https://get.rvm.io | bash -s stable
      - rvm install 2.2
      - sudo gem install jekyll
  pre_build:
    commands:
      - npm install -g gulp
      - npm install
  build:
    commands:
      - gulp build
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - dist/