version: 0.1

phases:
  install:
    commands:
      - sudo gem install jekyll
      - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
      - sudo apt-get install -y nodejs
  pre_build:
    commands:
      - npm install -g gulp
      - npm install
  build:
    commands:
      - gulp build
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - dist/